<?php
"
CREATE TABLE fields (
id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
field varchar(255),
describe varchar(255)
);


INSERT INTO fields (field, describe)
VALUES('id', '№');



INSERT INTO fields (
field, describe
)
VALUES('person_name', 'ПІБ');

INSERT INTO fields (
field, describe
)
VALUES('diagnosis', 'Діагноз');

INSERT INTO fields (
field, describe
)
VALUES('phone', 'Телефон');

INSERT INTO fields (
field, describe
)
VALUES('address', 'Адреса');

INSERT INTO fields (
field, describe
)
VALUES('dateofbirth', 'Дата_народження');

INSERT INTO fields (
field, describe
)
VALUES('gender', 'Стать');

INSERT INTO fields (
field, describe
)
VALUES('status', 'Статус');

INSERT INTO fields (
field, describe
)
VALUES('id_doctor', '№_доктора');
"
?>

