<?php
"CREATE TABLE Persons (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	person_name varchar(255),
	Diagnosis varchar(255),
	Phone varchar(255),
    Address varchar(255),
    dateofbirth varchar(255),
	Gender varchar(255),
	Status varchar(255),
	Id_Doctor int
)";