CREATE TABLE Users
(
id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
Login varchar(255) NOT NULL,
Password varchar(255),
DoctorId varchar(255),

CONSTRAINT login UNIQUE(login)
)


CONSTRAINT login
PRIMARY KEY (login) ( >= 3 )
UNIQUE(login)