<?php
"CREATE TABLE Persons (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	FirstName varchar(255),
    LastName varchar(255),
	Diagnosis varchar(255),
	Phone varchar(255),
    Address varchar(255),
    City varchar(255),
	Gender varchar(255),
	Status varchar(255),
	IdDoctor int
)";